language: java

jdk:
  - oraclejdk8

# install
before_install:
 - free -m
 - ls -la
 - cd OWLTools-Parent;mvn install -DskipTests=true;cd ..

# run tests
script:
  - cd OWLTools-Parent;mvn clean compile test
